{% set name = "specta" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e8114ca28f5a2da261b1d85598e78ae19bb967ff7a91e3619874f5e988e4aa1b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - nodejs
    - pip
    - jupyterlab >=4.0.0,<5
    - hatchling >=1.5.0
    - hatch-nodejs-version
    - hatch-jupyter-builder >=0.5
  run:
    - python >={{ python_min }}
    - jupyterlite-core >=0.6.0,<0.7

test:
  imports:
    - specta
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/trungleduc/specta
  summary: 'Dashboarding tool for JupyterLite'
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - trungleduc
