{% set name = "specta" %}
{% set version = "0.3.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3b50e1cee7f1ff2e80644c4a52f91496c02aec602b2b1b23e6950e3c39af56af

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - nodejs
    - pip
    - jupyterlab >=4.5.0,<5
    - hatchling >=1.5.0
    - hatch-nodejs-version
    - hatch-jupyter-builder >=0.5
  run:
    - python >={{ python_min }}
    - jupyterlite-core >=0.7.0,<0.8

test:
  imports:
    - specta
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/trungleduc/specta
  summary: 'Dashboarding tool for JupyterLite'
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - trungleduc
